### ISSUE TITLE
西文字体显示效果被破坏了

### ISSUE THREAD

**Issue by aimerneige** [loaden/best-fonts#1]
![image](https://user-images.githubusercontent.com/51701792/159517976-c80b363a-834d-46b8-8844-4650cb69919d.png)

```bash
aimerneige@pop-os ~
➜ neofetch
             /////////////                aimerneige@pop-os
         /////////////////////            -----------------
      ///////*767////////////////         OS: Pop!_OS 21.10 x86_64
    //////7676767676*//////////////       Host: TM1701
   /////76767//7676767//////////////      Kernel: 5.16.11-76051611-generic
  /////767676///*76767///////////////     Uptime: 6 mins
 ///////767676///76767.///7676*///////    Packages: 2422 (dpkg), 1 (brew), 70 (flatpak)
/////////767676//76767///767676////////   Shell: zsh 5.8
//////////76767676767////76767/////////   Resolution: 1920x1080
///////////76767676//////7676//////////   DE: GNOME 40.5
////////////,7676,///////767///////////   WM: Mutter
/////////////*7676///////76////////////   WM Theme: Adwaita
///////////////7676////////////////////   Theme: Mojave-dark [GTK2/3]
 ///////////////7676///767////////////    Icons: WhiteSur-dark [GTK2/3]
  //////////////////////'////////////     Terminal: alacritty
   //////.7676767676767676767,//////      Terminal Font: FiraCode Nerd Font Mono
    /////767676767676767676767/////       CPU: Intel i7-8550U (8) @ 4.000GHz
      ///////////////////////////         GPU: Intel UHD Graphics 620
         /////////////////////            GPU: NVIDIA GeForce MX250
             /////////////                Memory: 3230MiB / 15886MiB



```

**Comment by aimerneige** [comment]
emoji 也不能显示了
![image](https://user-images.githubusercontent.com/51701792/159653332-1c1ba792-3034-4e1d-b674-2e28420589b6.png)

**Comment by aimerneige** [comment]
我的建议是系统语言为中文且大量处理中文的场景下使用卸载脚本删除系统字体。

**Comment by loaden** [comment]
不能只拷贝配置，还需要使用这个项目中提供的字体，如果字体显示有问题，把多余的系统字体配置移除（会自动备份到.conf.d.bak）。

**Comment by loaden** [comment]
这两个问题能发个链接我来找下原因吗？

**Comment by aimerneige** [comment]
我做的操作:

1. 执行`fonts.sh`脚本
2. 执行`purge-fonts.sh`脚本（此处删除了大量包）
3. 显示异常，仔细阅读 `README` 后，使用`la`指令才发现项目下还有俩个隐藏目录 `.config` 和 `.local`
4. 完整拷贝字体和配置文件
5. 部分显示依然异常

我的系统语言是英语，查资料也用英文，中文场景不是很常见。

**Comment by aimerneige** [comment]
这俩天结束手头项目之后我会重新安装debian，那时再重新跑一下这个脚本，我来反馈一下结果。

**Comment by aimerneige** [comment]
西文显示和 emoji 的问题应该是 `purge-fonts.sh` 脚本关联删除了太多包了，我直接拷贝本项目字体和配置后，访问中文网页就可以实现截图中的效果，没有任何问题。

终端没有测试，因为我不用中文系统。

**Comment by loaden** [comment]
> 只拷贝配置文件的话，中文西文没问题，emoji 不能正常显示
> 
> ![image](https://user-images.githubusercontent.com/51701792/160878707-81c24eab-9da3-4697-8292-20b07b28d080.png)

因为我删除了系统的符号字体。如果只拷贝配置，是达不到我图片示例的效果的。
这个字体的效果，一定要配合我提供的字体。
具体请看下金步国先生的文章，他对字体的研究非常深入。
我和他有过交流，他的这篇文章，是半年的研究成果。
我主要是借用了他的成果。
